// Code generated by MockGen. DO NOT EDIT.
// Source: newsroom/newsroom.go

// Package mock_newsroom is a generated GoMock package.
package mock_newsroom

import (
	reflect "reflect"

	news "github.com/gaborszakacs/fakenews/news"
	gomock "github.com/golang/mock/gomock"
)

// MockNewsFeed is a mock of NewsFeed interface
type MockNewsFeed struct {
	ctrl     *gomock.Controller
	recorder *MockNewsFeedMockRecorder
}

// MockNewsFeedMockRecorder is the mock recorder for MockNewsFeed
type MockNewsFeedMockRecorder struct {
	mock *MockNewsFeed
}

// NewMockNewsFeed creates a new mock instance
func NewMockNewsFeed(ctrl *gomock.Controller) *MockNewsFeed {
	mock := &MockNewsFeed{ctrl: ctrl}
	mock.recorder = &MockNewsFeedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNewsFeed) EXPECT() *MockNewsFeedMockRecorder {
	return m.recorder
}

// TaggedWith mocks base method
func (m *MockNewsFeed) TaggedWith(tag news.Tag) []news.Story {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaggedWith", tag)
	ret0, _ := ret[0].([]news.Story)
	return ret0
}

// TaggedWith indicates an expected call of TaggedWith
func (mr *MockNewsFeedMockRecorder) TaggedWith(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaggedWith", reflect.TypeOf((*MockNewsFeed)(nil).TaggedWith), tag)
}

// MockReportAdder is a mock of ReportAdder interface
type MockReportAdder struct {
	ctrl     *gomock.Controller
	recorder *MockReportAdderMockRecorder
}

// MockReportAdderMockRecorder is the mock recorder for MockReportAdder
type MockReportAdderMockRecorder struct {
	mock *MockReportAdder
}

// NewMockReportAdder creates a new mock instance
func NewMockReportAdder(ctrl *gomock.Controller) *MockReportAdder {
	mock := &MockReportAdder{ctrl: ctrl}
	mock.recorder = &MockReportAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportAdder) EXPECT() *MockReportAdderMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *MockReportAdder) Add(report news.Report) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", report)
}

// Add indicates an expected call of Add
func (mr *MockReportAdderMockRecorder) Add(report interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockReportAdder)(nil).Add), report)
}
